### ISSUE TITLE
Include app in F-Droid

### ISSUE THREAD

**Issue by straycosmicllama** [OuterTune/OuterTune#82] opened 2024-10-31 04:28 UTC
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

I would be good to have this app added to Fdroid

### Why do you want this feature?

Support in Fdroid

### Additional information

It was mentioned [here](https://github.com/DD3Boh/OuterTune/issues/23) but nothing was discussed related to F-droid

**Comment by mikooomich** [comment] 2024-10-31 13:32
Duplicate of #23

**Closed as not planned by mikooomich** 2024-10-31 13:32 UTC
Labels: enhancement
