### ISSUE TITLE
Not all playlists are visible and adding a song replaces the playlist with the other one

### ISSUE THREAD

**Issue by petersamuel22** [OuterTune/OuterTune#39] opened 2024-09-09 02:35 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Go to library page.
Make 2 synced playlist.
Add a song to the visible one.

### Expected behavior

The playlists are both visible to the user and aren't substituted when the user adds songs to them.

### Actual behavior

Having 1 synchronized playlist in the library makes it invisible and adding a second one makes the first invisible and the second visible, adding a song to the visible one subsitutes it with the one that was previously invisible.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/c8036280-c1f0-4784-85db-4bb0bc9ca12b

### Logs

[log.txt](https://github.com/user-attachments/files/16924772/log.txt)

### OuterTune version

0.6.1

### Android version

14

**Comment by mikooomich** [comment] 2024-09-09 04:24
Duplicate of #28

**Closed as not planned** 2024-09-12 03:37 UTC
Labels: bug
